# Created by Jekyll Writer
title: 小说：孤子
author: 512Song
description: >
  This theme is disigned based on Mailbox Blog, and licensed under MIT. This
  theme is also default theme for new site created by Jekyll Writer.
permalink: '/:year/:month/:day/:title/'
paginate: 6
paginate_path: '/page/:num/'
twitter_username: jekyllwriter
github_username: jekyllwriter
gems:
  - jekyll-paginate
markdown: kramdown
baseurl: "/guzi"
theme: jekyll-theme-leap-day
excerpt_separator: "\n\n\n"
